### ISSUE TITLE
NetworkManager service should not be restarted if it is not installed

### ISSUE THREAD

**Issue by whiterm** [kubeforce/kubeforce#6]
Something is wrong in the playbook file
playbooky.aml
```
    - name: Copy NetworkManager files
      copy:
        src: "files{{ item }}"
        dest: "{{ item }}"
      when: "'NetworkManager.service' in ansible_facts.services"
      with_items:
        - /etc/NetworkManager/conf.d/
      notify:
        - Restart NetworkManager
```

on host
```bash
# systemctl status NetworkManager.service
Unit NetworkManager.service could not be found.
```

in the logs
```
TASK [Copy crictl files] *******************************************************
changed: [127.0.0.1] => (item=/etc/crictl.yaml)

TASK [Copy sysctl files] *******************************************************
changed: [127.0.0.1] => (item=/etc/sysctl.d/)

TASK [Copy containerd service files] *******************************************
changed: [127.0.0.1] => (item=/etc/containerd/config.toml)
changed: [127.0.0.1] => (item=/etc/systemd/system/containerd.service)

TASK [Copy kubernetes components] **********************************************
changed: [127.0.0.1] => (item=kubeadm)
changed: [127.0.0.1] => (item=kubelet)
changed: [127.0.0.1] => (item=kubectl)

TASK [Copy kubernetes service files] *******************************************
changed: [127.0.0.1] => (item=/etc/systemd/system/kubelet.service)
changed: [127.0.0.1] => (item=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf)

TASK [Copy NetworkManager files] ***********************************************
changed: [127.0.0.1] => (item=/etc/NetworkManager/conf.d/)

TASK [Start services, if not started] ******************************************
changed: [127.0.0.1] => (item=containerd.service)
changed: [127.0.0.1] => (item=kubelet.service)

RUNNING HANDLER [Restart containerd] *******************************************
changed: [127.0.0.1]

RUNNING HANDLER [Restart kubelet] **********************************************
changed: [127.0.0.1]

RUNNING HANDLER [Restart NetworkManager] ***************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service NetworkManager.service: host"}

RUNNING HANDLER [Reload sysctl] ************************************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=24   changed=19   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
